<?php /** @var \Vladimirl\Chatter\Block\Data $block */ ?>
<form id="vladimirl-chatter-form-chatter"
      method="post"
      autocomplete="off"
      action="<?= $block->escapeUrl($block->getUrl('vladimrl_chatter_controller/submit/submit')) ?>"
      data-mage-init='{"vladimirL_chatter_formChatter": {}}'
      onsubmit="return false"
>
    <div id="messages-list">
        <?php /** @var \Vladimirl\Chatter\Model\ChatMessage $massage */ ?>
        <?php foreach ($block->getChatMessage() as $massage): ?>
            <p><?= $massage; ?></p>
        <?php endforeach; ?>
    </div>
    <textarea id="message-input"
              placeholder="<?= $block->escapeHtml(__('Message')) ?>"
              name="text_request"
              data-validate="{required:true}"
    ></textarea>
    <button type="submit" id="send-message-button">
        <?= $block->escapeHtml(__('Send message')) ?></button>
    <button type="button" id="close-chatter-button">
        <?= $block->escapeHtml(__('Close chat')) ?></button>
</form>